name: shop_app
description: Fittin Graduate App
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  http: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  auto_route: ^7.7.0
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  elementary: ^2.0.0
  pinput: ^2.2.31
  decimal: ^2.3.3
  intl: ^0.18.1
  redux: ^5.0.0
  flutter_redux: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  auto_route_generator: ^7.2.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    
  fonts:
    - family: ShopAppIcons
      fonts:
        - asset: assets/fonts/ShopAppIcons.ttf